name: workflow

on:
    push:
        branches:
            - main
        path-ignore:
            - 'README.md'
    jobs:
        integration:
            name: Continuous Integration
            runs-on: ubuntu-latest
            steps:
              - name: Checkout Code
                uses: actions/checkout@v3

              - name: Link code
                run: echo "Linking repository"

              - name: Run unit tests
                run: echo "Runnig unit tests"